/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.integrador.animation;

import java.awt.Component;
import projeto.integrador.panel.panelmenuprinc.JpMenuPrinc;
import projeto.integrador.panel.panelsubmenuintra.JpSubMenuIntra;

/**
 *
 * @author Developer1
 */
public class TAnimation extends javax.swing.JFrame {

    private JpMenuPrinc pane1;
    private JpSubMenuIntra pane2;
     
    public TAnimation() {
        initComponents();
//        
        pane1 = new JpMenuPrinc();
        pane2 =  new JpSubMenuIntra();
//        
       jSlidingPanel1.setSlidingComponents(new Component[]{pane1, pane2});
        
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlidingPanel1 = new projeto.integrador.util.JSlidingPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2560, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSlidingPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSlidingPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static projeto.integrador.util.JSlidingPanel jSlidingPanel1;
    // End of variables declaration//GEN-END:variables
}
